// Message type constants — must stay in sync with core/wire/types.go
export const TypeInput    = 'input'
export const TypeOutput   = 'output'
export const TypeCwd      = 'cwd'
export const TypeExitCode = 'exit_code'
export const TypeGit      = 'git'
export const TypeNode     = 'node'
export const TypeGo       = 'go'
export const TypePython   = 'python'
export const TypeDocker   = 'docker'
export const TypeK8s      = 'k8s'
export const TypePrompt   = 'prompt'
export const TypeTui      = 'tui'
export const TypeConfig   = 'config'
export const TypeKill     = 'kill'
export const TypeResize   = 'resize'

export const TypeAIAppend       = 'ai_append'
export const TypeAISuggestion   = 'ai_suggestion'
export const TypeAISuggestError = 'ai_suggest_error'
export const TypeAIExplanation  = 'ai_explanation'

