// Message type constants — must stay in sync with core/wire/types.go
export const TypeInput    = 'input'
export const TypeRawInput = 'raw_input'
export const TypeOutput   = 'output'
export const TypeCwd      = 'cwd'
export const TypeExitCode = 'exit_code'
export const TypeGit      = 'git'
export const TypeNode     = 'node'
export const TypeGo       = 'go'
export const TypePython   = 'python'
export const TypeDocker   = 'docker'
export const TypeK8s      = 'k8s'
export const TypePrompt   = 'prompt'
export const TypeTui      = 'tui'
export const TypeConfig   = 'config'
export const TypeKill     = 'kill'
export const TypeResize   = 'resize'

export const TypeRust     = 'rust'
export const TypePhp      = 'php'
export const TypeJava     = 'java'
export const TypeKotlin   = 'kotlin'
export const TypeHaskell  = 'haskell'
export const TypeC        = 'c'
export const TypeConda    = 'conda'

export const TypeAIAppend       = 'ai_append'
export const TypeAISummary      = 'ai_summary'
export const TypeAIStatus       = 'ai_status'
export const TypeAISuggestion   = 'ai_suggestion'
export const TypeAISuggestError = 'ai_suggest_error'
export const TypeAIExplanation  = 'ai_explanation'
export const TypeAIBannerStart  = 'ai_banner_start'
export const TypeAIBannerToken  = 'ai_banner_token'
export const TypeAIBannerCancel = 'ai_banner_cancel'

export const TypeSessionID = 'session_id'

export const TypeAsk      = 'ask'
export const TypeAskChunk = 'ask_chunk'
export const TypeAskDone  = 'ask_done'
export const TypeAskError = 'ask_error'

export const TypeAIAnalyze  = 'ai_analyze'
export const TypeAIAnalysis = 'ai_analysis'

export const TypeAIRiskCheck       = 'ai_risk_check'
export const TypeAIRiskExplanation = 'ai_risk_explanation'
export const TypeSummarize  = 'summarize'

export const TypeNLQuery  = 'nl_query'
export const TypeNLResult = 'nl_result'
export const TypeNLError  = 'nl_error'

export const TypeGhostQuery  = 'ghost_query'
export const TypeGhostResult = 'ghost_result'

export const TypeAskGlobal        = 'ask_global'
export const TypeAskSuggest       = 'ask_suggest'
export const TypeAskSuggestResult = 'ask_suggest_result'

export const TypeHistorySearch       = 'history_search'
export const TypeHistorySearchResult = 'history_search_result'
