// Message type constants — must stay in sync with core/wire/types.go
export const TypeInput    = 'input'
export const TypeOutput   = 'output'
export const TypeCwd      = 'cwd'
export const TypeExitCode = 'exit_code'
export const TypePrompt   = 'prompt'
export const TypeTui      = 'tui'
export const TypeConfig   = 'config'
export const TypeKill     = 'kill'
export const TypeResize   = 'resize'
