export const THEME_IDS = [
  'default',
  'catppuccin-mocha',
  'tokyo-night',
  'gruvbox',
  'nord',
  'dracula',
]

export const THEMES = {
  'default': {
    id: 'default',
    name: 'Default',
    colors: {
      bgBase:        '#141416',
      bgSurface:     '#141416',
      bgElevated:    '#1c1c1f',
      border:        '#2a2a2e',
      textPrimary:   '#e8e8ea',
      textSecondary: '#9898a6',
      textMuted:     '#6b6b72',
      accent:        '#7c6af7',
      onAccent:      '#ffffff',
      error:         '#f85149',
    },
  },
  'catppuccin-mocha': {
    id: 'catppuccin-mocha',
    name: 'Catppuccin Mocha',
    colors: {
      bgBase:        '#1e1e2e',
      bgSurface:     '#181825',
      bgElevated:    '#313244',
      border:        '#45475a',
      textPrimary:   '#cdd6f4',
      textSecondary: '#a6adc8',
      textMuted:     '#585b70',
      accent:        '#cba6f7',
      onAccent:      '#1e1e2e',
      error:         '#f38ba8',
    },
  },
  'tokyo-night': {
    id: 'tokyo-night',
    name: 'Tokyo Night',
    colors: {
      bgBase:        '#1a1b26',
      bgSurface:     '#16161e',
      bgElevated:    '#24283b',
      border:        '#292e42',
      textPrimary:   '#c0caf5',
      textSecondary: '#9aa5ce',
      textMuted:     '#565f89',
      accent:        '#7aa2f7',
      onAccent:      '#1a1b26',
      error:         '#f7768e',
    },
  },
  'gruvbox': {
    id: 'gruvbox',
    name: 'Gruvbox Dark',
    colors: {
      bgBase:        '#282828',
      bgSurface:     '#1d2021',
      bgElevated:    '#3c3836',
      border:        '#504945',
      textPrimary:   '#ebdbb2',
      textSecondary: '#bdae93',
      textMuted:     '#7c6f64',
      accent:        '#d3869b',
      onAccent:      '#282828',
      error:         '#fb4934',
    },
  },
  'nord': {
    id: 'nord',
    name: 'Nord',
    colors: {
      bgBase:        '#2e3440',
      bgSurface:     '#242933',
      bgElevated:    '#3b4252',
      border:        '#434c5e',
      textPrimary:   '#eceff4',
      textSecondary: '#d8dee9',
      textMuted:     '#616e88',
      accent:        '#88c0d0',
      onAccent:      '#2e3440',
      error:         '#bf616a',
    },
  },
  'dracula': {
    id: 'dracula',
    name: 'Dracula',
    colors: {
      bgBase:        '#282a36',
      bgSurface:     '#21222c',
      bgElevated:    '#373844',
      border:        '#44475a',
      textPrimary:   '#f8f8f2',
      textSecondary: '#6272a4',
      textMuted:     '#44475a',
      accent:        '#bd93f9',
      onAccent:      '#282a36',
      error:         '#ff5555',
    },
  },
}
